services:
  nginx:
    build: ./nginx
    restart: "always"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_files:/var/www/html
    ports:
      - 443:443
  wordpress:
    build: ./wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    healthcheck:
      test: ["CMD", "pgrep", "-f", "php-fpm"]
      interval: 1s
      timeout: 2s
      retries: 20
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_user_password
  mariadb:
    build: ./mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 2s
      retries: 20
    secrets:
      - db_root_password
      - db_user_password

volumes:
  wordpress_files:
  mariadb_data:

networks:
  default: 

secrets:
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt